import { CaseStudy } from '@/types';
import { getContrastTextColor } from '@/utils/getContrastTextColor';

export const caseStudies: CaseStudy[] = [
  {
    id: 'port-phillip',
    title: 'City of Port Phillip',
    description:
      'A brand new digital ecosystem including multiple websites and customer facing online services.',
    hero: 'A brand new digital ecosystem including multiple websites and customer facing online services.',
    color: '#13676f',
    contrastTextColor: getContrastTextColor('#13676f'),
    visit: { name: 'portphillip.vic.gov.au', to: 'https://www.portphillip.vic.gov.au/' },
    representation: { name: 'VERSA Agency', to: 'https://versa.agency/' },
    output: ['Intranet', 'Website'],
    industry: ['Government'],
    capability: ['Strategy', 'UI/UX'],
    method: [
      'Artefact Review',
      'Concept Usability Testing',
      'Data Analytics Review',
      'Heuristics Evaluation',
      'IA: Card Sorting',
      'IA: Tree Testing',
      'Journey Mapping',
      'Persona Development',
      'Requirements Gathering',
      'Roadmapping',
      'Stakeholder Interviews',
      'User Interviews',
    ],
  },
  {
    id: 'bank-vic',
    title: 'Bank Vic',
    description:
      'A future-proof platform, with endless customisation and a personalised experience.',
    hero: 'BankVic is a 100% member owned bank focused on serving police, health, emergency and public services, as well as their family and friends. Their aim is to build healthy communities that are financially, socially and environmentally sustainable.',
    color: '#279cd0',
    contrastTextColor: getContrastTextColor('#279cd0'),
    visit: { name: 'bankvic.com.au', to: 'https://www.bankvic.com.au/' },
    representation: { name: 'VERSA Agency', to: 'https://versa.agency/' },
    output: ['Website'],
    industry: ['Banking & Finance'],
    capability: ['Strategy'],
    method: [
      'Artefact Review',
      'Competitor Analysis',
      'Concept Usability Testing',
      'Data Analytics Review',
      'Heuristics Evaluation',
      'IA: Tree Testing',
      'Journey Mapping',
      'Persona Development',
      'Requirements Gathering',
      'Stakeholder Interviews',
      'User Interviews',
      'IA: Card Sorting',
    ],
  },
  {
    id: 'lumea',
    title: 'Lumea',
    description:
      'A market first solution that’s accelerate Australia toward a smarter energy future.',
    hero: 'A market first solution that’s accelerate Australia toward a smarter energy future.',
    color: '#222f32',
    contrastTextColor: getContrastTextColor('#222f32'),
    visit: { name: 'lumea.com.au', to: 'http://www.lumea.com.au/' },
    representation: { name: 'VERSA Agency', to: 'https://versa.agency/' },
    output: ['Website'],
    industry: ['Sports & Entertainment'],
    capability: ['UI/UX', 'Branding'],
    method: [
      'Artefact Review',
      'Requirements Gathering',
      'Persona Development',
      'IA: Card Sorting',
      'IA: Tree Testing',
      'Competitor Analysis',
    ],
  },
  {
    id: 'bupa',
    title: 'Bupa',
    description:
      'A reimagined way of working and subsequently a platform to proper service its users needs.',
    hero: 'A reimagined way of working and subsequently a platform to proper service its users needs.',
    color: '#046ebc',
    contrastTextColor: getContrastTextColor('#046ebc'),
    visit: { name: 'bupaoptical.bupa.com.au', to: 'https://bupaoptical.bupa.com.au/' },
    representation: { name: '(i.e.,)', to: 'https://www.ie.com.au/' },
    output: ['Website'],
    industry: ['Sports & Entertainment'],
    capability: ['UI/UX'],
    method: [
      'Artefact Review',
      'Requirements Gathering',
      'Persona Development',
      'IA: Card Sorting',
      'IA: Tree Testing',
      'Competitor Analysis',
    ],
  },
];
