import { OtherWork } from '@/types';
import { getContrastTextColor } from '@/utils/getContrastTextColor';
import aGentlemansTonic from '@/assets/images/a-gentlemans-tonic.png';
import enduro from '@/assets/images/enduro.png';
import distill from '@/assets/images/distill.png';
import local from '@/assets/images/local.png';
import logosAndSymbols from '@/assets/images/logos-and-symbols.png';
import illustrations from '@/assets/images/illustrations.png';

export const otherWorks: OtherWork[] = [
  {
    id: 'a-gentlemans-tonic',
    img: aGentlemansTonic,
    title: 'A Gentleman’s Tonic',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#4f5543',
    contrastTextColor: getContrastTextColor('#4f5543'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-1.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-2.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-3.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-4.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-5.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-6.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-7.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-8.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-9.jpg',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-10.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/a-gentlemans-tonic/a-gentlemans-tonic-11.png',
    ],
  },
  {
    id: 'enduro',
    img: enduro,
    title: 'Enduro',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#68e0e0',
    contrastTextColor: getContrastTextColor('#68e0e0'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-1.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-2.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-3.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-4.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-5.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-6.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-7.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-8.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-9.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-10.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-11.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-12.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-13.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-14.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-15.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-16.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-17.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/enduro/enduro-18.png',
    ],
  },
  {
    id: 'distill',
    img: distill,
    title: 'Distill',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#191919',
    contrastTextColor: getContrastTextColor('#191919'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-1.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-2.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-3.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-4.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-5.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-6.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-7.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-8.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-9.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-10.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-11.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-12.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-13.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-14.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-15.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-16.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-17.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-18.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-19.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-20.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/distill/distill-21.png',
    ],
  },
  {
    id: 'logos-and-symbols',
    img: logosAndSymbols,
    title: 'Logos & Symbols',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#000000',
    contrastTextColor: getContrastTextColor('#000000'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-1.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-2.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-3.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-4.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-5.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-6.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-7.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-8.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-9.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-10.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-11.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/logos-and-symbols/logos-and-symbols-12.png',
    ],
  },
  {
    id: 'local',
    img: local,
    title: 'Local',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#5cad66',
    contrastTextColor: getContrastTextColor('#5cad66'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-1.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-2.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-3.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-4.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-5.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-6.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-7.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-8.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-9.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-10.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-11.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-12.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-13.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-14.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-15.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-16.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-17.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-18.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/local/local-19.png',
    ],
  },
  {
    id: 'illustration',
    img: illustrations,
    title: 'Illustration',
    hero: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus erat nec orci tincidunt, eu posuere orci semper.',
    color: '#111111',
    contrastTextColor: getContrastTextColor('#111111'),
    otherImages: [
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-0.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-1.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-2.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-3.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-4.png',
      'https://mattk-portfolio-media.s3.ap-southeast-2.amazonaws.com/other-works/illustrations/illustrations-5.png',
    ],
  },
];
